language: generic
os: linux

before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.30.2/hugo_0.30.2_Linux-64bit.tar.gz
  - mkdir hugo
  - tar -xvf hugo_0.30.2_Linux-64bit.tar.gz -C ./hugo
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/hugo

script: hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: page-src